coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/tests/**"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/vite-env.d.ts"
  - "**/main.tsx"

