services:
  portfolio-tracker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_POLYGON_API_KEY=${VITE_POLYGON_API_KEY}
        - VITE_POLYGON_BASE_URL=${VITE_POLYGON_BASE_URL}
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: portfolio-tracker
